import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('.artifacts', {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8000/');
  await page.waitForSelector('#office-viewer');
  const frame = await (await page.locator('#office-viewer').elementHandle()).contentFrame();
  await frame.waitForFunction(() => window.cleanroom?.ready, {}, {timeout:90000});
  const initial = await frame.evaluate(() => window.cleanroom.metadata());
  assert.equal(initial.scene_id, 'office-rebuild');
  assert.equal(initial.navigation_mode, 'free_flight');
  await frame.locator('#viewport canvas').click({position:{x:600,y:180}});
  await page.keyboard.down('d'); await page.waitForTimeout(500); await page.keyboard.up('d');
  const moved = await frame.evaluate(() => window.cleanroom.metadata());
  assert.ok(Math.hypot(...moved.position.map((value,i)=>value-initial.position[i])) > .01, 'Keyboard translates the camera');
  await frame.locator('#presentation-before').click();
  const before = await frame.evaluate(() => window.cleanroom.metadata());
  assert.equal(before.revision_id, 'original');
  assert.deepEqual(before.position, moved.position, 'Revision change preserves exploration position');
  await frame.locator('#presentation-after').click();
  assert.equal((await frame.evaluate(() => window.cleanroom.metadata())).revision_id,initial.revision_id);
  await frame.locator('#probe-reset').click();
  await page.waitForTimeout(500);
  await page.screenshot({path:'.artifacts/demo-3d-desktop.png',fullPage:true});
  await page.locator('#compare-tab').click();
  await page.waitForFunction(() => [...document.images].every(i=>i.complete&&i.naturalWidth>0));
  await page.getByLabel('Before and after comparison').fill('25');
  assert.match(await page.locator('#before-image').getAttribute('style'),/75%/);
  await page.locator('#explore-tab').click();
  await page.locator('summary').click();
  await page.locator('.loop-diagram').waitFor({state:'visible'});
  await page.locator('summary').click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const mobileBefore=await frame.evaluate(()=>window.cleanroom.metadata());
  const touch=frame.getByRole('button',{name:'Move backward',exact:true});
  await touch.dispatchEvent('pointerdown',{pointerId:1});
  await page.waitForTimeout(300);
  await touch.dispatchEvent('pointerup',{pointerId:1});
  const mobileAfter=await frame.evaluate(()=>window.cleanroom.metadata());
  assert.ok(Math.hypot(...mobileAfter.position.map((value,i)=>value-mobileBefore.position[i]))>.01);
  await page.screenshot({path:'.artifacts/demo-3d-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('3D demo passed: embedded office, keyboard/touch movement, before/after at same position, comparison, diagram, responsive layout.');
} finally {await browser.close();}
